---
# necessary steps to configure the role

- name: install base condarc
  become: no
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  become: no
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH="{{ miniconda_home }}/bin:$PATH"
    state: present

#- name: create environments
#  sudo: no
#  shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} {{ item.pkgs }} creates={{ miniconda_home }}/envs/{{ item.name }}"
#  when: miniconda_installed | success
#  with_items: miniconda_environments
